# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 23.1a1
    hooks:
      - id: black
        name: Black code formatter
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Flake8 code linter
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0
    hooks:
      - id: pylint
